apiVersion: v1
kind: Service
metadata:
  name: mlp-serving
  namespace: mlp
  labels:
    app.kubernetes.io/name: mlp-serving
spec:
  selector:
    app.kubernetes.io/name: mlp-serving
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
